---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: timbru31/java-node
    tag: 'latest'

inputs:
- name: osb-checker-kotlin
- name: overview-broker

run:
  path: overview-broker/ci/scripts/conformance.sh
